### ISSUE TITLE
Optimized and enhanced version of the `pyproject.toml` file for the [AGR project]

### ISSUE THREAD

**Issue by exatonix** [hbiyik/agr#7]
(https://github.com/hbiyik/agr/blob/master/pyproject.toml), with improvements for efficiency, maintainability, and modern Python packaging standards:

---

### **Enhanced `pyproject.toml`**
```toml
[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agr"
version = "0.1.0"  # Consider dynamic versioning via `setuptools-scm`
description = "A Git-centric package manager for Arch Linux with dynamic versioning and cross-compilation"
readme = "README.md"
authors = [
  { name = "Huseyin Biyik", email = "your-email@example.com" }
]
license = { text = "GPL-3.0-or-later" }
keywords = ["archlinux", "package-manager", "git", "aur", "cross-compilation"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Programming Language :: Python :: 3.10",
  "Topic :: System :: Archiving :: Packaging",
  "Topic :: Utilities"
]
dependencies = [
  "gitpython>=3.1.0",
  "pyalpm>=0.10.0",  # Arch Linux package metadata parsing
  "python-magic>=0.4.0",
  "tomli>=2.0.0",    # For Python <3.11 compatibility
  "typing_extensions>=4.0.0; python_version<'3.11'",
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/hbiyik/agr"
Documentation = "https://github.com/hbiyik/agr/wiki"
Issues = "https://github.com/hbiyik/agr/issues"

[project.scripts]
agr = "agr.cli:main"

[tool.setuptools]
packages = ["agr"]
package-dir = { "" = "src" }

# ========================
# Development Tools Config
# ========================
[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 120
known_first_party = "agr"

[tool.mypy]
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
warn_redundant_casts = true

[tool.pytest.ini_options]
addopts = "-v --cov=agr --cov-report=term-missing"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.coverage.run]
source = ["agr"]
branch = true
omit = ["**/__main__.py"]

[tool.ruff]
line-length = 120
target-version = "py310"
select = [
  "E", "F", "W",    # Basic errors
  "I",              # Import order
  "UP",             # Modern Python features
  "PL",             # Pylint conventions
]
ignore = ["E501"]   # Let Black handle line length
```

---

### **Key Improvements**:
1. **Modern Packaging Standards**:
   - Added explicit `build-system` configuration for reproducibility.
   - Structured `[project]` metadata with classifiers and URLs.
   - Added type hints support via `typing_extensions`.

2. **Dependency Management**:
   - Pinned minimum versions (`gitpython>=3.1.0`) for stability.
   - Added `pyalpm` for Arch package metadata parsing.

3. **Developer Experience**:
   - Integrated static analysis tools (`mypy`, `ruff`).
   - Configured `black` and `isort` for consistent formatting.
   - Added test coverage with `pytest` and `coverage`.

4. **Cross-Compilation Readiness**:
   - Explicit Python version (`>=3.10`) for Arch Linux compatibility.
   - Type checking enforced for safer container/cross-compilation logic.

5. **Documentation**:
   - Added URLs for GitHub docs/issues.
   - README.md explicitly declared.

---

### **Recommended Next Steps**:
1. **Dynamic Versioning**:  
   Replace hardcoded `version` with `setuptools-scm` for Git-based versioning:
   ```toml
   [tool.setuptools_scm]
   version_scheme = "no-guess-dev"
   ```

2. **Pre-commit Hooks**:  
   Add a `.pre-commit-config.yaml` to enforce formatting/linting:
   ```yaml
   repos:
     - repo: https://github.com/psf/black
       rev: 23.3.0
       hooks: [{ id: black }]
     - repo: https://github.com/charliermarsh/ruff-pre-commit
       rev: v0.0.272
       hooks: [{ id: ruff }]
   ```

3. **CI/CD Pipeline**:  
   Create a GitHub Actions workflow to run tests/linters on PRs.

4. **Arch-Specific Metadata**:  
   Add `alpm` hooks for `pacman` integration (if applicable).

Would you like me to expand on any of these areas? 🚀
